
# Use distroless as minimal base image to package the api binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
FROM gcr.io/distroless/static:nonroot 
WORKDIR /
COPY api .
USER nonroot:nonroot

ENTRYPOINT ["/api"]
