// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Jwt struct {
	User       string    `json:"user"`
	Properties []*string `json:"properties"`
}

type NewJwt struct {
	User  string   `json:"user"`
	Roles []string `json:"roles"`
}
