permissions:
- del-text
- del-photo
- jwt-query
- rbac-query
- rbac-mutate
- the-bugle-del-media
- the-bugle-mod-story
- the-bugle-mod-photo
- the-bugle-mod-staff
roles:
  the-bugle-chief-editor:
    permissions:
    - the-bugle-del-media
    - the-bugle-mod-staff
    parents:
    - the-bugle-editor
    - the-bugle-photographer
  the-bugle-editor:
    permissions:
    - the-bugle-mod-story
    parents: []
  jwt:
    permissions:
    - jwt-query
    parents: []
  the-bugle-photographer:
    permissions:
    - the-bugle-mod-photo
    parents: []
  rbac-ro:
    permissions:
    - rbac-query
    parents: []
  rbac-rw:
    permissions:
    - rbac-mutate
    parents:
    - rbac-ro
