permissions:
- add-text
- edit-text
- insert-photo
- add-photo
- edit-photo
- del-text
- del-photo
- JWT_QUERY
- RBAC_QUERY
- RBAC_MUTATE

roles:
    jwt:
        permissions:
        - JWT_QUERY
    rbac-ro:
        permissions:
        - RBAC_QUERY
    rbac-rw:
        parents:
        - rbac-ro
        permissions:
        - RBAC_MUTATE
    editor:
        permissions:
        - add-text
        - edit-text
        - insert-photo 
    photographer:
        permissions:
        - add-photo
        - edit-photo
    chief-editor:
        parents:
        - editor
        - photographer
        permissions:
        - del-text
        - del-photo


