resources:
- api.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: api
  newName: jeremymarshall/gqlgen-jwt
  newTag: latest
configMapGenerator:
- envs:
  - api.env
  name: apienv
- files:
  - all.yaml
  name: gorbac-yaml
